"""add allow_notifications to users

Revision ID: f1810365a4b5
Revises: 0003_add_decks
Create Date: 2026-07-31 17:57:11.993602

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f1810365a4b5"
down_revision: str | None = "0003_add_decks"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cards_source_file"), table_name="cards")
    op.drop_index(op.f("ix_cards_user_id"), table_name="cards")
    op.drop_index(op.f("ix_decks_user_id"), table_name="decks")
    op.drop_index(op.f("ix_progress_next_review"), table_name="progress")
    op.alter_column(
        "review_sessions",
        "card_ids",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_review_sessions_user_id"), table_name="review_sessions")
    op.drop_constraint(op.f("review_sessions_session_id_key"), "review_sessions", type_="unique")
    op.drop_index(op.f("ix_review_sessions_session_id"), table_name="review_sessions")
    op.create_index(
        op.f("ix_review_sessions_session_id"), "review_sessions", ["session_id"], unique=True
    )
    op.add_column(
        "users",
        sa.Column("allow_notifications", sa.Boolean(), server_default="true", nullable=False),
    )
    op.drop_constraint(op.f("users_telegram_id_key"), "users", type_="unique")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=False)
    op.create_unique_constraint(
        op.f("users_telegram_id_key"), "users", ["telegram_id"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("users", "allow_notifications")
    op.drop_index(op.f("ix_review_sessions_session_id"), table_name="review_sessions")
    op.create_index(
        op.f("ix_review_sessions_session_id"), "review_sessions", ["session_id"], unique=False
    )
    op.create_unique_constraint(
        op.f("review_sessions_session_id_key"),
        "review_sessions",
        ["session_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_review_sessions_user_id"), "review_sessions", ["user_id"], unique=False
    )
    op.alter_column(
        "review_sessions",
        "card_ids",
        existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.create_index(op.f("ix_progress_next_review"), "progress", ["next_review"], unique=False)
    op.create_index(op.f("ix_decks_user_id"), "decks", ["user_id"], unique=False)
    op.create_index(op.f("ix_cards_user_id"), "cards", ["user_id"], unique=False)
    op.create_index(op.f("ix_cards_source_file"), "cards", ["user_id", "source_file"], unique=False)
    # ### end Alembic commands ###
